services:
  - type: web
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://daxpatel2300005_db_user:vi21FPWuweDVZDuz@cluster0.zdtxlyg.mongodb.net/portfolio?retryWrites=true&w=majority&appName=Cluster0
      - key: NODE_VERSION
        value: 20.x
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
